### ISSUE TITLE
Vagrant up stuck on ssh keys

### ISSUE THREAD

**Issue by scout-external-services** [MatthewHartstonge/rancheros-box#6]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'MatthewHartstonge/RancherOS'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'MatthewHartstonge/RancherOS' is up to date...
==> default: Setting the name of the VM: rancheros-box_default_1494808953150_81995
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: rancher
    default: SSH auth method: private key

**Comment by matthewhartstonge** [comment]
Hey there @scout-external-services did you use `vagrant ssh` to access the box? or are you trying to add your own ssh keys?

**Comment by obenziane2** [comment]
this is happening when running `vagrant up` and have not passed the provisioning part yet

**Comment by matthewhartstonge** [comment]
Oky doke, thanks for the report. I'll have a look at it later this week.

**Comment by matthewhartstonge** [comment]
@scout-external-services @obenziane2 I've had a play round with re-building the box and pulling the cloud hosted versions. Both times I manage to get access via `vagrant ssh` with the default `Vagrantfile`. Due to the minimilist implementation (i.e. you can ssh into it) it doesn't have any real support for Virtualbox. I hope to play around and create a RancherOS Guest capabilities plugin that makes it a little more configurable under vagrant. 
For now, I've been solely using it for spinning up hosts and starting an agent, then managed under rancher.
Sidenote: due to it's implementation, I don't know if provisioners will work as I tested that.

**Comment by matthewhartstonge** [comment]
No response
